engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Alias:
        enabled: false
      Rubocop/Style/LineEndConcatenation:
        enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
    exclude_paths:
    - spec/**/*_spec.rb
