engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
    exclude_paths:
    - spec/**/*_spec.rb
ratings:
  paths:
  - app/**
  - "**.rb"
