require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WhiteCardsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WhiteCard. As you add validations to WhiteCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WhiteCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all white_cards as @white_cards" do
      white_card = WhiteCard.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:white_cards)).to eq([white_card])
    end
  end

  describe "GET #show" do
    it "assigns the requested white_card as @white_card" do
      white_card = WhiteCard.create! valid_attributes
      get :show, params: {id: white_card.to_param}, session: valid_session
      expect(assigns(:white_card)).to eq(white_card)
    end
  end

  describe "GET #new" do
    it "assigns a new white_card as @white_card" do
      get :new, params: {}, session: valid_session
      expect(assigns(:white_card)).to be_a_new(WhiteCard)
    end
  end

  describe "GET #edit" do
    it "assigns the requested white_card as @white_card" do
      white_card = WhiteCard.create! valid_attributes
      get :edit, params: {id: white_card.to_param}, session: valid_session
      expect(assigns(:white_card)).to eq(white_card)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WhiteCard" do
        expect {
          post :create, params: {white_card: valid_attributes}, session: valid_session
        }.to change(WhiteCard, :count).by(1)
      end

      it "assigns a newly created white_card as @white_card" do
        post :create, params: {white_card: valid_attributes}, session: valid_session
        expect(assigns(:white_card)).to be_a(WhiteCard)
        expect(assigns(:white_card)).to be_persisted
      end

      it "redirects to the created white_card" do
        post :create, params: {white_card: valid_attributes}, session: valid_session
        expect(response).to redirect_to(WhiteCard.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved white_card as @white_card" do
        post :create, params: {white_card: invalid_attributes}, session: valid_session
        expect(assigns(:white_card)).to be_a_new(WhiteCard)
      end

      it "re-renders the 'new' template" do
        post :create, params: {white_card: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested white_card" do
        white_card = WhiteCard.create! valid_attributes
        put :update, params: {id: white_card.to_param, white_card: new_attributes}, session: valid_session
        white_card.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested white_card as @white_card" do
        white_card = WhiteCard.create! valid_attributes
        put :update, params: {id: white_card.to_param, white_card: valid_attributes}, session: valid_session
        expect(assigns(:white_card)).to eq(white_card)
      end

      it "redirects to the white_card" do
        white_card = WhiteCard.create! valid_attributes
        put :update, params: {id: white_card.to_param, white_card: valid_attributes}, session: valid_session
        expect(response).to redirect_to(white_card)
      end
    end

    context "with invalid params" do
      it "assigns the white_card as @white_card" do
        white_card = WhiteCard.create! valid_attributes
        put :update, params: {id: white_card.to_param, white_card: invalid_attributes}, session: valid_session
        expect(assigns(:white_card)).to eq(white_card)
      end

      it "re-renders the 'edit' template" do
        white_card = WhiteCard.create! valid_attributes
        put :update, params: {id: white_card.to_param, white_card: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested white_card" do
      white_card = WhiteCard.create! valid_attributes
      expect {
        delete :destroy, params: {id: white_card.to_param}, session: valid_session
      }.to change(WhiteCard, :count).by(-1)
    end

    it "redirects to the white_cards list" do
      white_card = WhiteCard.create! valid_attributes
      delete :destroy, params: {id: white_card.to_param}, session: valid_session
      expect(response).to redirect_to(white_cards_url)
    end
  end

end
